AWSTemplateFormatVersion: 2010-09-09
Description: |
  Basic front end for a simple web app.

Resources:
  
  WebAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: frontend-registro
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  WebAppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebAppBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
            Action: s3:GetObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref WebAppBucket, '/*']]

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Access identity for CloudFront distribution

  WebAppCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          AllowedMethods:
            - POST
            - GET
            - HEAD
          Compress: 'true'
          DefaultTTL: 30
          ForwardedValues:
            QueryString: 'false'
          MinTTL: 0
          SmoothStreaming: 'false'
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
        Enabled: 'true'
        HttpVersion: http2
        Origins:
          - DomainName: !GetAtt WebAppBucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
        


Outputs:
  WebAppCloudFrontDistribution:
    Description: The URL of the website
    Value: !GetAtt WebAppCloudFrontDistribution.DomainName
    Export:
      Name: !Sub ${AWS::StackName}-WebAppCloudFrontDistribution
  WebAppBucket:
    Description: The URL of the website
    Value: !Ref WebAppBucket
    Export:
      Name: !Sub ${AWS::StackName}-WebAppBucket
  WebAppBucketPolicy:
    Description: The URL of the website
    Value: !Ref WebAppBucketPolicy
    Export:
      Name: !Sub ${AWS::StackName}-WebAppBucketPolicy
