AWSTemplateFormatVersion: 2010-09-09
Description: a simple web registration app
  
Resources:

  BackEndStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://raw.githubusercontent.com/ELRuncho/registro/main/registrobackend/BackEndStack.yaml

  FrontEndStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://raw.githubusercontent.com/ELRuncho/registro/main/registrobackend/FrontEndStack.yaml

Outputs:
  site:
    Value: !GetAtt FrontEndStack.Outputs.WebAppCloudFrontDistribution